## Logistic Regression - Diabetes prediction

In [5]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
import pickle
import json

In [6]:
df = pd.read_csv('E:\Velocity\Diabetes_prediction\datasets_228_482_diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [8]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


## Train Test Split

In [10]:
x = df.drop('Outcome',axis = 1)
y = df['Outcome']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)

In [11]:
x_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
602            1      124             74             36        0  27.8   
429            1       95             82             25      180  35.0   
623            0       94             70             27      115  43.5   
209            7      184             84             33        0  35.5   
589            0       73              0              0        0  21.1   
..           ...      ...            ...            ...      ...   ...   
534            1       77             56             30       56  33.3   
584            8      124             76             24      600  28.7   
493            4      125             70             18      122  28.9   
527            3      116             74             15      105  26.3   
168            4      110             66              0        0  31.9   

     DiabetesPedigreeFunction  Age  
602                     0.100   30  
429                     0.233   43  
623                     0.347   21  
209                     0.355   41  
589                     0.342   25  
..                        ...  ...  
534                     1.251   24  
584                     0.687   52  
493                     1.144   45  
527                     0.107   24  
168                     0.471   29  

[614 rows x 8 columns]

## Model Training

In [12]:
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [13]:
# Testing Data Evaluation
y_pred = model.predict(x_test)

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.88      0.84       109
           1       0.63      0.49      0.55        45

    accuracy                           0.77       154
   macro avg       0.72      0.68      0.70       154
weighted avg       0.75      0.77      0.76       154



In [15]:
# Training Data Evaluation
y_pred_train = model.predict(x_train)

from sklearn.metrics import classification_report
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.80      0.87      0.83       391
           1       0.73      0.61      0.67       223

    accuracy                           0.78       614
   macro avg       0.76      0.74      0.75       614
weighted avg       0.77      0.78      0.77       614



## Testing on Single Row

In [16]:
x.head(1).T

0
Pregnancies                 6.000
Glucose                   148.000
BloodPressure              72.000
SkinThickness              35.000
Insulin                     0.000
BMI                        33.600
DiabetesPedigreeFunction    0.627
Age                        50.000

In [18]:
x.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')

In [19]:
Pregnancies = 5
Glucose = 145
BloodPressure = 74
SkinThickness = 30
Insulin = 0
BMI = 31
DiabetesPedigreeFunction = 0.65
Age = 48
# Outcome = ?

In [20]:
test_array = np.array([5,145,74,30,0,31,0.65,48], ndmin = 2)
test_array

array([[  5.  , 145.  ,  74.  ,  30.  ,   0.  ,  31.  ,   0.65,  48.  ]])

In [21]:
model.predict(test_array)

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [22]:
test_array = np.zeros(x.shape[1])
test_array[0] = Pregnancies
test_array[1] = Glucose
test_array[2] = BloodPressure
test_array[3] = SkinThickness
test_array[4] = Insulin
test_array[5] = BMI
test_array[6] = DiabetesPedigreeFunction
test_array[7] = Age

test_array

array([  5.  , 145.  ,  74.  ,  30.  ,   0.  ,  31.  ,   0.65,  48.  ])

In [24]:
result = model.predict([test_array])
print(f'Result is', result)

Result is [1]


C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [30]:
project_data = {'columns': list(x.columns)}
project_data

{'columns': ['Pregnancies',
  'Glucose',
  'BloodPressure',
  'SkinThickness',
  'Insulin',
  'BMI',
  'DiabetesPedigreeFunction',
  'Age']}

In [31]:
with open('Linear_model.pkl', 'wb') as f:
    pickle.dump(model, f)

In [32]:
with open('project_data.json', 'w') as f:
    json.dump(project_data, f)